ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', 'web')),
    path('users/', include('users.urls', 'users')),
]
if settings.DEBUG:  # Solo en modo desarrollo
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# USER_ Admin
# PASS: Admin.-2024

web/urls.py
from django.urls import path, include

from web import views

app_name = 'web'

urlpatterns = [
   path('', views.index, name='index'),
   path('product_per_category/<int:category_id>/', views.product_per_category, name='product_per_category'),
   path('product_per_name/', views.product_per_name, name='product_per_name'),
   path('product_detail/<int:product_id>/', views.product_detail, name='product_detail'),
   path('cart/', views.cart, name='cart'),
   path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
   path('delete_cart/<int:product_id>/', views.delete_cart, name='delete_cart'),
   path('clear_cart/', views.clear_cart, name='clear_cart'),
]

web/templates/includes/footer.html
{% load static %}
<!--footer-->
<footer class="footer-section">
        <div class="container">
            <div class="footer-cta pt-5 pb-5">
                <div class="row">
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="single-cta">
                            <i class="fas fa-map-marker-alt"> </i>
                            <div class="cta-text">
                                <h4> Dirección </h4>
                                <span> Av Independencia 1988 <span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="single-cta">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <div class="cta-text">
                                <h4> Telefono</h4>
                                <span> +56 952034094 </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="single-cta">
                            <i class="far fa-envelope-open"> </i>
                            <div class="cta-text">
                                <h4> Email </h4>
                                <span> mail@info.com </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-content pt-5 pb-5">
                <div class="row footer-row">
                    <div class="col-xl-4 col-lg-4 mb-50">
                        <div class="footer-widget">
                            <div class="footer-logo">
                                <a href="index.html"> <img src="{% static 'img/logo-footer.png' %}" class="img-fluid" alt="logo"> </a>
                            </div>
                            <div class="footer-text">
                                <p> Lorem ipsum dolor sit amet, consec tetur adipisicing elit, sed do eiusmod tempor incididuntut consec tetur adipisicing
                                elit,Lorem ipsum dolor sit amet. </p>
                            </div>
                            <div class="footer-social-icon">
                                <span> Siguenos</span>
                                <a href="#"> <i class="fa fa-facebook-square" aria-hidden="true"></i> </i> </a>
                                <a href="#"> <i class="fa fa-instagram" aria-hidden="true"></i> </i> </a>
                                <a href="#"> <i class="fa fa-linkedin-square" aria-hidden="true"></i> </i> </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-6 mb-30">
                        <div class="footer-widget">
                            <div class="footer-widget-heading">
                                <h3> Categorias </h3>
                            </div>
                            <ul>
                                <li> <a href="#"> Todas las Parrillas </a> </li>
                                <li> <a href="#"> Parrillas a Gas </a> </li>
                                <li> <a href="#"> Parrillas a Carbon</a> </li>
                                <li> <a href="#"> Parrillas a Electricas</E></a> </li>

                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-6 mb-50">
                        <div class="footer-widget">
                            <div class="footer-widget-heading">
                                <h3> Subscribete </h3>
                            </div>
                            <div class="footer-text mb-25">
                                <p> Don?t miss to subscribe to our new feeds, kindly fill the form below. </p>
                            </div>
                            <div class="subscribe-form">
                                <form action="#">
                                    <input type="text" placeholder="Email Address">
                                    <button> <i class="fa fa-paper-plane-o" aria-hidden="true"></i> </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-area">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 text-center text-lg-left">
                        <div class="copyright-text">
                             <p> Copyright &copy; {% now "Y" %}, All Rights Reserved </p>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 d-none d-lg-block text-right">
                        <div class="footer-menu">
                            <ul>
                                <li> <a href="#"> Home </a> </li>
                                <li> <a href="#"> Terms </a> </li>
                                <li> <a href="#"> Privacy </a> </li>
                                <li> <a href="#"> Policy </a> </li>
                                <li> <a href="#"> Contact </a> </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

web/templates/includes/header.html
{% load static %}
    <!--header-->
    <div class="site-header">

        <p class="h-logo">
            <a href="/"><img src="{% static 'img/logo.png' %}" alt="EdShop"></a>
        </p><!--
    No Space
    --><div class="h-shop">

        <form method="post" action="{% url 'web:product_per_name' %}" class="h-search" id="h-search">
            {% csrf_token %}
            <input type="text" name="name" placeholder="Buscar...">
            <button type="submit"><i class="ion-search"></i></button>
        </form>

        <ul class="h-shop-links">
            <li class="h-search-btn" id="h-search-btn"><i class="ion-search"></i></li>
            {% include 'includes/header_carrito.html' %}
            <li class="h-shop-icon h-profile">
                <a href="auth.html" title="My Account">
                    <i class="ion-android-person"></i>
                </a>
                <ul class="h-profile-links">
                    <li><a href="/login">Ingresa</a></li>
                    <li><a href="/login">Registrate</a></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </li>




        </ul>
    </div></div>

web/templates/includes/header_carrito.html
<li class="h-cart">
    <a class="cart-contents" href="cart.html">
        <p class="h-cart-icon">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <span>{{request.session.cart.items|length}}</span>
        </p>
        <p class="h-cart-total">${{request.session.cartTotalAmount}}</p>
    </a>
    <div class="widget_shopping_cart">
        <div class="widget_shopping_cart_content">
            <ul class="cart_list">
                {% for key,value in request.session.cart.items %}
                <li>
                    <a href="{% url 'web:delete_cart' value.product_id %}" class="remove">&times;</a>
                    <a href="#">
                        <img src="{{value.image}}" alt="">
                        {{ value.name }}
                    </a>
                    <span class="quantity">{{value.quantity}} &times; ${{value.subtotal}}</span>
                </li>
                {% endfor %}
            </ul>
            <p class="total"><b>Total:</b> ${{request.session.cartTotalAmount}}</p>
            <p class="buttons">
                <a href="{% url 'web:cart' %}" class="button">Ver Carrito</a>
                <a href="#" class="button">Pedido</a>
            </p>
        </div>
    </div>
</li>

web/templates/includes/navbar.html
<!--navbar-->
<div class="container-fluid page-styling site-header-before">
    <div class="row">
        <div class="col-lg-4">
            <ul class="links_list links_list-align-left align-center-desktop topbar-social">
                <li>
                    <p class="links_list-value">

                </li>
            </ul>
        </div>
        <div class="col-lg-8 contactos">
            <ul class="links_list links_list-align-right align-center-desktop topbar-contacts">
                <li>
                    <p class="links_list-label">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                    </p>
                    <p class="links_list-value">
                        <a href="http://maps.google.com" target="_blank" rel="nofollow">Calle Independencia 1122</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </p>
                    <p class="links_list-value">
                        <a href="mailto:support@email.com">Support@Email.com</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        <i class="fa fa-mobile" aria-hidden="true"></i>
                    </p>
                    <p class="links_list-value">
                        <a href="tel:4785929899">+56 952034094</a>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>

web/templates/includes/relacionados.html
<h2 class="prod-related-ttl">Related Products</h2>
    <div class="row prod-items prod-items-4">
        <article class="cf-sm-6 cf-md-6 cf-lg-3 col-xs-6 col-sm-6 col-md-6 col-lg-3 sectgl-item sectgl-item">
            <div class="sectgl prod-i">
                <div class="prod-i-top">
                    <a class="prod-i-img" href="product.html">
                        <img src="http://placehold.it/290x258" alt="">
                    </a>
                    <div class="prod-i-actions">
                        <div class="prod-i-actions-in">
                            <div class="prod-li-favorites">
                                <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                            </div>
                            <p class="prod-quickview">
                                <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Quick View</span></a>
                            </p>
                            <p class="prod-i-cart">
                                <a href="#" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Add to Cart</span></a>
                            </p>
                            <p class="prod-li-compare">
                                <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                            </p>
                        </div>
                    </div>
                    <p class="prod-i-badge"><span>Sale</span></p>
                </div>
                <div class="prod-i-bot">
                    <div class="prod-i-info">
                        <p class="prod-i-price">$70.00</p>
                        <p class="prod-i-categ"><a href="catalog-gallery.html">Electricity</a></p>
                    </div>
                    <h3 class="prod-i-ttl"><a href="product.html">Universal Plug</a></h3>
                </div>
            </div>
        </article>
    </div>