ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', 'web')),
    path('users/', include('users.urls', 'users')),
]
if settings.DEBUG:  # Solo en modo desarrollo
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# USER_ Admin
# PASS: Admin.-2024

web/urls.py
from django.urls import path, include

from web import views

app_name = 'web'

urlpatterns = [
   path('', views.index, name='index'),
   path('product_per_category/<int:category_id>/', views.product_per_category, name='product_per_category'),
   path('product_per_name/', views.product_per_name, name='product_per_name'),
   path('product_detail/<int:product_id>/', views.product_detail, name='product_detail'),
   path('cart/', views.cart, name='cart'),
   path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
   path('delete_cart/<int:product_id>/', views.delete_cart, name='delete_cart'),
   path('clear_cart/', views.clear_cart, name='clear_cart'),
]

web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Carrito</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Carrito</li>
    </ul>
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="product.html" class="prod-li-img">
                        <img src="{{value.image}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{value.category}}</a>
                            </p>
                            <h3><a href="{% url 'web:product_detail' value.product_id %}">{{value.name}}</a></h3>
                        </div><!--
                    No Space
                    -->
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio Unid</p>
                                <p class="prod-li-price">${{value.price}}</p>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    Cant:
                                    <input type="text" value="{{value.quantity}}">

                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Total</p>
                                <p class="prod-li-total">${{value.subtotal}}</p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Acciones</p>
                                <a class="checkout-button button" href="{% url 'web:product_detail' value.product_id %}">Modificar</a>
                            </div>
                        </div><!--
                No Space
                -->
                    </div>
                    <div class="prod-li-info">
                        <p class="prod-li-add">
                            <a href="{% url 'web:delete_cart' value.product_id %}" class="button hover-label prod-addbtn"><i
                                    class="icon ion-close-round"></i><span>Eliminar</span></a>
                        </p>
                    </div>
                </div>
            </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <form class="form-coupon" method="post" action="{% url 'web:cart' %}">
                {% csrf_token %}
                <div class="coupon-container">
                    <input type="text" name="coupon" placeholder="Cupón de descuento">
                    <button type="submit" class="button btn-descuento">
                        <i class="fa fa-check-circle-o" aria-hidden="true"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:clear_cart' %}" class="checkout-button button">Borrar todo</a>
            <a href="" class="checkout-button button">Realizar Pedido</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{request.session.cartTotalAmount}}</p>
            </div>
        </div>
    </div>


</div>
    <div class="row">
                <div class="col-12 alertas">
                {% if request.session.coupon_code %}
                    <p class="cart-totals-ttl">Cupón aplicado: {{ request.session.coupon_code }}</p>
                {% endif %}
                {% if message %}
                    <p class="message">{{ message }}</p>
                {% endif %}
                </div>
    </div>

{% endblock %}

web/templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Checkout OK</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>COMPRA</li>
    </ul>
    <h2>GRACIAS POR TU COMPRA</h2>    
{% endblock %}

web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
        <div class="section-top">

            <h1 class="maincont-ttl">Catalogo</h1>
            <ul class="b-crumbs">
                <li><a href="/">Inicio</a></li>
                <li>Catalogo</li>
            </ul>
        </div>
        <!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
        <div class="section-wrap-withsb">
            <aside class="blog-sb-widgets section-sb" id="section-sb">
                <div class="theiaStickySidebar">
                    <p class="section-filter-toggle filter_hidden">
                        <a href="#" id="section-filter-toggle-btn">Filtros</a>
                    </p>
                    <div class="section-filter">
                        <div class="section-filter">
                            {% include 'includes/catalogo/categorias.html' %}
                        </div>
                    </div>
                </div>
            </aside>        <div class="section-list-withsb" id="section-list-withsb">
            <div class="theiaStickySidebar">
                {% include 'includes/catalogo/catalogo.html' %}
            </div><!-- .theiaStickySidebar -->
        </div><!-- .section-list-withsb -->
        </div><!-- .section-wrap-withsb -->
{% endblock %}

web/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deverom</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <link rel="icon" type="image/png" sizes="16x16"  href="{% static 'img/favicon.png' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">

    <!-- enlace a google font lato -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.formstyler.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mThumbnailScroller.css' %}">
    <link rel="stylesheet" href="{% static 'css/chosen.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements-media.css' %}">

</head>
<body>
<div id="page" class="site">

    {% include 'includes/navbar.html' %}

    {% include 'includes/header.html' %}

    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="cont maincont">
                    {% block content %}
                    {% endblock %}
                </div>
            </main><!-- #main -->
        </div><!-- #primary -->

    </div><!-- #content -->
</div><!-- #page -->

    {% include 'includes/footer.html' %}
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

web/templates/pedido.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="maincont-ttl">PEDIDO NRO : {{pedido.nro_pedido}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Pedido</li>
    </ul>
<div class="page-styling">
    <div class="woocommerce prod-litems section-list">
            <h2>Fecha : {{pedido.fecha_registro}}</h2>
            {% for detalle in pedido.pedidodetalle_set.all %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="{{ detalle.producto.imagen.url }}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{detalle.producto.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{ detalle.producto.nombre }}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">${{detalle.producto.precio}}</p>
                            </div>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{detalle.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{detalle.subtotal}}</p>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
    </div>
    <div class="cart-actions">
            <div class="cart-collaterals">
                {{ formpaypal.render }}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">${{pedido.monto_total}}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

web/templates/plantilla.html
{% extends 'layout.html' %}
{% block content %}
{% endblock %}

web/templates/producto.html
{% extends 'layout.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li><a href="/">Catalog</a></li>
        <li>Producto</li>
    </ul>
    <article>
    <div class="prod">
        <div class="prod-slider-wrap prod-slider-shown">
            <div class="flexslider prod-slider" id="prod-slider">
                <ul class="slides">
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="#">
                            {% if product.image and product.image.name %}
                                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                            {% else %}
                                <img src="{% static 'img/default.png' %}" alt="Imagen por defecto">
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="#">
                            {% if product.image and product.image.name %}
                                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                            {% else %}
                                <img src="{% static 'img/default.png' %}" alt="Imagen por defecto">
                            {% endif %}
                        </a>
                    </li>
                </ul>
                <div class="prod-slider-count"><p>
                    <span class="count-cur">1</span> / <span class="count-all">2</span></p><p class="hover-label prod-slider-zoom">
                    <i class="icon ion-search"></i><span>Zoom In</span></p></div>
            </div>
            <div class="flexslider prod-thumbs" id="prod-thumbs">
                <ul class="slides">
                    <li>
                        {% if product.image and product.image.name %}
                            <img src="{{ product.image.url }}" alt="{{ product.name }}">
                        {% else %}
                            <img src="{% static 'img/default.png' %}" alt="Imagen por defecto">
                        {% endif %}
                    </li>
                    <li>
                        {% if product.image and product.image.name %}
                            <img src="{{ product.image.url }}" alt="{{ product.name }}">
                        {% else %}
                            <img src="{% static 'img/default.png' %}" alt="Imagen por defecto">
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>

        <div class="prod-cont">
            <div class="prod-rating-wrap">
                <p data-rating="4" class="prod-rating">
                    <i class="rating-ico" title="1"></i>
                    <i class="rating-ico" title="2"></i>
                    <i class="rating-ico" title="3"></i>
                    <i class="rating-ico" title="4"></i>
                    <i class="rating-ico" title="5"></i>
                </p>
                <p class="prod-rating-count">7</p>
            </div>
            <p class="prod-categs"><a href="#">{{product.category}}</a></p>
            <h1>{{ product.name }}</h1>
            <div class="variations_form cart">
                <p class="prod-price">${{product.price}}</p>
                <p class="prod-excerpt">{{ product.description }}
                    <a id="prod-showdesc" class="prod-excerpt-more" href="#">read more</a></p>
<div class="prod-add">
    <form action="{% url 'web:add_cart' product.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="button"><i class="icon ion-android-cart"></i> Agregar al Carrito</button>
        <p class="qnt-wrap prod-li-qnt">
            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
            <!-- Establece el valor del input como la cantidad obtenida del carrito -->
            <input type="text" name="quantity" value="{{ quantity }}">
            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
        </p>
    </form>
</div>
            </div>
            <div class="prod-props">
                <dl class="product_meta">
                    
                    
                </dl>
            </div>
        </div>
    </div>


    

</article>

{% endblock %}