ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', 'web')),
    path('users/', include('users.urls', 'users')),
]
if settings.DEBUG:  # Solo en modo desarrollo
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# USER_ Admin
# PASS: Admin.-2024

web/urls.py
from django.urls import path, include

from web import views

app_name = 'web'

urlpatterns = [
   path('', views.index, name='index'),
   path('product_per_category/<int:category_id>/', views.product_per_category, name='product_per_category'),
   path('product_per_name/', views.product_per_name, name='product_per_name'),
   path('product_detail/<int:product_id>/', views.product_detail, name='product_detail'),
   path('cart/', views.cart, name='cart'),
   path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
   path('delete_cart/<int:product_id>/', views.delete_cart, name='delete_cart'),
   path('clear_cart/', views.clear_cart, name='clear_cart'),
]

web/models.py
from django.db import models


class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    discount = models.FloatField()  # Porcentaje de descuento, ej. 10 para 10%
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.code} - {self.discount}%"

class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='Nombre Categoria')
    register_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        
        
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    name = models.CharField(max_length=200, verbose_name='Nombre de Producto')
    description = models.TextField(null=True)
    price = models.DecimalField(max_digits=9, decimal_places=0)
    register_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='products',blank=True)
    
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
    

web/templates/includes/catalogo/catalogo.html
{% load static %}
<div class="row prod-items prod-items-3">
    {% for product in products %}
    <article class="cf-sm-4 cf-md-4 cf-lg-4 col-xs-6 col-sm-4 col-md-4 col-lg-4 sectgl-item">
        <div class="sectgl prod-i">
            <div class="prod-i-top">
                <a class="prod-i-img" href="{% url 'web:product_detail' product.id %}">
                    {% if product.image and product.image.name %}
                        <img src="{{ product.image.url }}" alt="{{ product.name }}">
                    {% else %}
                        <img src="{% static 'img/default.png' %}" alt="Imagen por defecto">
                    {% endif %}
                </a>
                <div class="prod-i-actions">
                    <div class="prod-i-actions-in">
                        <p class="prod-i-cart">
                            <a href="{% url 'web:add_cart' product.id %}" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Añadir al carrito</span></a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="prod-i-bot">
                <div class="prod-i-info">
                    <p class="prod-i-price">${{product.price}}</p>
                    <p class="prod-i-categ"><a href="#">{{product.category}}</a></p>
                </div>
                <h3 class="prod-i-ttl"><a href="{% url 'web:product_detail' product.id %}">{{product.name}}</a></h3>
            </div>
        </div>
    </article>
    {% endfor %}
</div>

web/templates/includes/catalogo/categorias.html
<div class="blog-sb-widget multishopcategories_widget">
    <h3 class="widgettitle">Categorias</h3>
    <div class="section-sb-current">
        <ul class="section-sb-list">
            {% for category in categories %}
            <li>
                <a href="{% url 'web:product_per_category' category.id %}">
                    <span class="section-sb-label">{{category.name}}
                        <span class="count">{{category.product_set.all.count}}</span>
                    </span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>